version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: rizen_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rizen
    ports:
      - "5432:5432"
    volumes:
      - rizen_pgdata:/var/lib/postgresql/data

volumes:
  rizen_pgdata:
